from rich import print


print(':paths\\NTphonePy')
print('>"NTphonePy/.calc"')
print('>>"NTphonePy/.calc/-nums"')
print('>>"NTphonePy/.calc/-/"')
print('>>"NTphonePy/.calc/-clas"')
print('...')
print('>"NTphonePy/.seconds"')
print('...')
print('>"NTphonePy/.store"')
print('>>"NTphonePy/.store/.down"')
print('>>>"NTphonePy/.store/.down/-musicman"')
print('>>>"NTphonePy/.store/.down/-brouser"')
print('>>>"NTphonePy/.store/.down/-lenning"')
print('>>>"NTphonePy/.store/.down/-dayandtime"')
print('...')
print('>>"NTphonePy/.store/.open"')
print('>>>"NTphonePy/.store/.open/-musicman"')
print('>>>"NTphonePy/.store/.open/-brouser"')
print('>>>"NTphonePy/.store/.open/-lenning"')
print('>>>"NTphonePy/.store/.open/-dayandtime"')
print('...')
print('>>"NTphonePy/.store/.del"')
print('>>>"NTphonePy/.store/.del/-musicman"')
print('>>>"NTphonePy/.store/.del/-brouser"')
print('>>>"NTphonePy/.store/.del/-lenning"')
print('>>>"NTphonePy/.store/.del/-dayandtime"')
print('...')
print('>>"NTphonePy/.store/.delall"')
print('>>"NTphonePy/.store/.dict"')
print('>>"NTphonePy/.store/.phone"   :|exit')
print('>>"NTphonePy/.store/.exitph"   :|exit')
print('...')
print('>"NTphonePy/.info"')
print('...')
print('>"NTphonePy/.note"')
print('>>"NTphonePy/.note/-write"')
print('>>"NTphonePy/.note/-read"')
print('>>"NTphonePy/.note/-delete"')
print('>>>"NTphonePy/.note/-delete/-y"')
print('>>>"NTphonePy/.note/-delete/-n"')
print('...')
print('>"NTphonePy/.files"')
print('...')
print('>"NTphonePy/.anim"')
print('>>"NTphonePy/.anim/-explos"')
print('>>"NTphonePy/.anim/-granata"')
print('...')
print('>"NTphonePy/.exit"   :|exit')
print('if :|exit: ./quit')
print()
print()
print('Press Enter to continue...')
input()