from rich import print
from time import sleep
def pos_1():
	print('[yellow]   ______')
	print('[yellow]  /      \ ')
	print('[yellow] /  .   . \ ')
	print('[yellow]|     |    |')
	print('[yellow]|   \____/ |')
	print('[yellow] \        /')
	print('[yellow]  \______/')
	print('[yellow]    |  |')
	sleep(0.5)
def pos_2():
	print('[yellow]   ______')
	print('[yellow]  /      \ ')
	print('[yellow] /  |   | \ ')
	print('[yellow]|   __|___ |')
	print('[yellow]|   \____/ |')
	print('[yellow] \        /')
	print('[yellow]  \______/')
	print('[yellow]    |  |')
	sleep(0.5)
def pos_3():
	print('[yellow]   ______')
	print('[yellow]  /  _  _\ ')
	print('[yellow] /  |_||_|\ ')
	print('[yellow]|     ||   |')
	print('[yellow]|   \____/ |')
	print('[yellow] \        /')
	print('[yellow]  \______/')
	print('[yellow]    |  |')
	sleep(0.5)
def pos_4():
	print('[yellow]   ______')
	print('[yellow]  /      \ ')
	print('[yellow] /  \   / \ ')
	print('[yellow]|     |    |')
	print('[yellow]|   \____/ |')
	print('[yellow] \        /')
	print('[yellow]  \______/')
	print('[yellow]    |  |')
	sleep(0.5)
def pos_5():
	print('[yellow]   _   __')
	print('[yellow]  / |_|  \ ')
	print('[yellow] /  [] []_\ ')
	print('[yellow]|     |  |__')
	print('[yellow]|   \____/ |')
	print('[yellow] \        /')
	print('[yellow]  \______/')
	print('[yellow]    |  |')
	sleep(0.5)
def pos_6():
	print('[yellow]   ______')
	print('[yellow]  //     \\\ ')
	print('[yellow] /   .  . \\\ ')
	print('[yellow]||     |    ||')
	print('[yellow]||     |    ||')
	print('[yellow] \\\  ___   //')
	print('[yellow]  \\\______//')
	print('[yellow]    |  |')