from playsound import playsound
from rich import print
from time import sleep

def start():
	print('[dim green]             |_[_]')
	print('[dim green]            /|__\ ')
	print('[dim green]           /_|__|\ ')
	print('[dim green]          /__|__|_\ ')
	print('[dim green]         /|__|__|__\ ')
	print('[dim green]        /_|__|__|__|\ ')
	print('[dim green]       |__|__|__|__|_| ')
	print('[dim green]       |__|__|__|__|_|')
	print('[dim green]        \_|__|__|__|/')
	print('[dim green]         \|__|__|__/')
	print('[dim green]          \__|__|_/')
	print('[dim green]             \__/')
	sleep(0.1)
def pos_2():
	sleep(0.2)
	print('[dim yellow]     \        [dim green]|_[_][dim yellow] /')
	print('[dim yellow]            [dim green]/|__\ [dim yellow]     /')
	print('[dim yellow]      \    [dim green]/_|__|\ [dim yellow]')
	print('[dim yellow]          [dim green]/__|__|_\ [dim yellow]  /')
	print('[dim yellow]      \  [dim green]/|__|__|__\ [dim yellow]')
	print('[dim yellow]        [dim green]/_|__|__|__|\ [dim yellow]   -  -')
	print('[dim yellow]    -  [dim green]|__|__|__|__|_| [dim yellow]   -')
	print('[dim yellow]       [dim green]|__|__|__|__|_| [dim yellow]  -')
	print('[dim yellow] -      [dim green]\_|__|__|__|/ [dim yellow]  \ ')
	print('[dim yellow]       / [dim green]\|__|__|__/ [dim yellow]')
	print('[dim yellow]          [dim green]\__|__|_/ [dim yellow]   \ ')
	print('[dim yellow]    /        [dim green]\__/ [dim yellow]  \ ')
	sleep(0.3)
def pos_3():
	print('[dim red]     \        [red]|_[_][dim red] /')
	print('[dim yellow]            [dim green]/|__\ [dim yellow]     /')
	print('[yellow]      \    [dim green]/_ __|\ [dim red]')
	print('[dim yellow]          [dim green]/_ |_  _\ [dim yellow]  /')
	print('[yellow]      \  [dim green]/  _| _| _\ [dim red]')
	print('[yellow]        [dim green]/_| [yellow]_ \ [dim green] |_ |\ [dim yellow]   -  -')
	print('[dim red]    -  [dim green]|__|_ [red]|-  _ [dim green]| _ _| |[red]   -')
	print('[dim yellow]       [dim green]|__|__| _|_ | | [dim yellow]  -')
	print('[dim yellow] -      [dim green]\_|_  __  _|/ [dim yellow]  \ ')
	print('[yellow]       / [dim green]\|__  _|  / [yellow]')
	print('[dim red]          [dim green]\__|__|_/ [dim red]   \ ')
	print('[dim yellow]    /        [dim green]\__/ [yellow]  \ ')
	sleep(0.7)
def pos_4():
	print('[red]  \  \   \  |  |    |  |  |   /   /  /  /  -')
	print('[red] - + \  \  \ - | -- --- = + | / //  /    / -- -')
	print('[red] -{ = \ \  \\ | [  ] { | |  /  /  / / /  -- - --')
	print('[red]--  _ \\ \ \  \ \{ = | | _ | -  | /   / // / - ---')
	print('[red] __ _ - --- : __ } = \ |  | |  _  / // ==-=--')
	print('[red] - -  - -- - ---= _ [bold red]/ \ [normal red]- - - --- _ = ')
	print('[red] -=-=--  =  _  -- -[bold red]|   |[normal red] =  --  - _ _ = ')
	print('[red] / // / / - - - - -[bold red]|   | [normal red]\   - -= - - - -')
	print('[red] - -- -- - -- -- - [bold red]\___/ [normal red] - - = -=+ - --: -')
	sleep(1)
def music():
	playsound('animations\\explos.mp3', False) 
