from rich.console import Console
cns = Console()

if True:
	from time import sleep
	import           os
	cns.print('[green]cc xtype-code NTphonePy')
	cns.print('[cyan]file crashall.py')
	cns.log('[red]Программа поддерживается с версии 1.5.')
	
	'''dr = __file__[0:__file__.find('crashall.py')]
	cns.print('[magenta]directory: [italic]', dr)
	cns.print('[red]Вы действительно хотите удалить NTphonePy1.4 (y/n):')
	ans = input('')
	if ans == 'y':
		cns.print('[magenta]Пожалуйста, укажите директорию этого файла: (без названия файла, слеш - "\\\\", в конце еще один двойной слеш.)')
		dr = input()
		cns.log('delete calc...')
		os.remove(dr+'calc\__pycache__\convertation.cpython-310.pyc')
		os.remove(dr+'calc\__pycache__\troecrat.cpython-310.pyc')
		os.remove(dr+'calc\neat_troecrat.png')
		os.remove(dr+'calc\troecrat.py')
		os.remove(dr+'calc\convertation.py')
		os.rmdir(dr+'calc\__pycache__')
		os.rmdir(dr+'calc')
		sleep(0.5)
		cns.log('delete animations...')
		os.remove(dr+'animations\explos.py')
		os.remove(dr+'animations\granata.py')
		os.remove(dr+'animations\emoji.py')
		os.remove(dr+'animations\explos.mp3')
		os.remove(dr+'animations\__pycache__\emoji.cpython-310.pyc')
		os.remove(dr+'animations\__pycache__\granata.cpython-310.pyc')
		os.remove(dr+'animations\__pycache__\explos.cpython-310.pyc')
		os.rmdir(dr+'animations\__pycache__')
		os.rmdir(dr+'animations')
		sleep(0.2)
		cns.log('delete store...')
		os.remove(dr+)
		os.rmdir(dr+'day_and_time')
		os.rmdir(dr+'musicmanager')
		os.rmdir(dr+'brouser')
		os.rmdir(dr+'lenning')
		os.remove(dr+'data.txt')
		sleep(0.8)
		cns.log('delete paths.py...')
		os.remove(dr+'paths.py')
		sleep(0.1)
		cns.log('delete filesmanager.py...')
		os.remove(dr+'filesmanager.py')
		cns.log('delete all music...')
		os.remove(dr+'error.mp3')
		os.remove(dr+'start.mp3')
		sleep(0.5)
		cns.print('[red]Все доп. файлы удалены. Удалить основные файлы? (y/n):')
		a = input()
		if a == 'y':
			cns.log('delete opent.py...')
			os.remove(dr+'opent.py')
			sleep(0.2)
			cns.log('delete init.py...')
			os.remove(dr+'init.py')
			sleep(0.9)
			cns.log('[green] info|     Все файлы успешно удалены.')
			input('Press Enter to CONTINUE >')
			quit()
except PermissionError:
	cns.log('PERMISSION error: отказано в доступе')
except:
	cns.log('SYSTEM error')'''
input('Press Enter to CONTINUE >')
quit()